### ISSUE TITLE
bytes32[] memory proofs;这块能解释下吗？？ 批量领取NFT空投的

### ISSUE THREAD

**Issue by dawnvi** [ericet/cosmos-learn#2]
bytes32[] memory proofs;

**Comment by ericet** [comment]
你放错地方了，你说的是那个multiclaim的库？一般领取需要前端计算一个proof，来领取空投什么的。有些proof不需要填

**Comment by dawnvi** [comment]
哦哦 好的 。。 谢谢

ericet ***@***.***> 于2022年4月12日周二 21:57写道：
