### ISSUE TITLE
e大这些api能兼容evmos和dym这些有evm地址的网络么

### ISSUE THREAD

**Issue by likieyes** [ericet/cosmos-learn#7]
对于dym网络是没法直接使用的，自己折腾好久也搞不定。请教e大这些api如何能兼容dym网络，包括send ,delegate,claim这些操作。感谢

**Comment by ericet** [comment]
没明白你的意思，代码支持evmos和dymension上的操作

**Comment by likieyes** [comment]
不好意思e大，是我自己的使用问题。确实可以支持dymension上的操作。十分感谢e大
